export const ISAUTHORIZATION = 'USER/ISAUTHORIZATION';
export const FETCH_USER_DATA = 'USER/FETCH_USER_DATA';
export const USER_LOGIN = 'USER/USER_LOGIN';
export const USER_PASSWORD = 'USER/USER_PASSWORD';
export const SHOW_SPINNER = 'APP/SHOW_SPINNER';
export const HIDE_SPINNER = 'APP/HIDE_SPINNER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';
